# https://cloud.google.com/build/docs/build-config-file-schema
steps:
  - name: 'node:16.15.0'
    entrypoint: yarn
    args: ['sample-docs', 'build:dev']

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--verbosity', 'debug', 'docs/sample-docs/app.yaml']

timeout: '1600s'
