# https://cloud.google.com/build/docs/build-config-file-schema
steps:
  - name: 'node:16.15.0'
    entrypoint: yarn
    args: ['sample-csr', 'build:dev']

  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      ['app', 'deploy', '--verbosity', 'debug', 'services/sample-csr/app.yaml']

timeout: '1600s'
